# Generated by Django 4.2 on 2024-12-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_guests_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='check_in',
            new_name='checkin_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out',
            new_name='checkout_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='number_of_guests',
            new_name='guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
    ]
