# Generated by Django 4.2 on 2024-12-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_rename_check_in_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
