# Generated by Django 4.2 on 2024-12-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_amenities_property_rules_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='image_url',
            field=models.URLField(default='https://media.istockphoto.com/id/2155879454/photo/this-is-an-exterior-photo-of-a-home-for-sale-in-beverly-hills-ca.webp?a=1&b=1&s=612x612&w=0&k=20&c=GvT1GQsxPREVk5rWMjlZaZHJH8TSpBDagNgZDg1NxyE=', max_length=500),
            preserve_default=False,
        ),
    ]
