# Generated by Django 4.2 on 2024-12-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_property_image_property_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='location',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
