# Generated by Django 4.2 on 2024-12-20 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
