# Generated by Django 4.2 on 2024-12-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='price_per_night',
        ),
    ]
