# Generated by Django 4.2 on 2024-12-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_remove_property_price_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image_url',
            field=models.URLField(max_length=1000),
        ),
    ]
